version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: eventmaster_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=eventmaster
      - POSTGRES_USER=eventmaster
      - POSTGRES_PASSWORD=eventmaster123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventmaster"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eventmaster_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=True
      - POSTGRES_HOST=db
      - DJANGO_SETTINGS_MODULE=eventmaster.settings.development
    depends_on:
      db:
        condition: service_healthy
