# Generated by Django 5.0.8 on 2025-10-19 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("description", models.TextField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("conference", "Conference"),
                            ("workshop", "Workshop"),
                            ("seminar", "Seminar"),
                            ("meetup", "Meetup"),
                            ("hackathon", "Hackathon"),
                        ],
                        default="conference",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(db_index=True)),
                ("end_date", models.DateTimeField(db_index=True)),
                ("registration_start", models.DateTimeField()),
                ("registration_end", models.DateTimeField()),
                ("venue_name", models.CharField(max_length=200)),
                ("venue_address", models.TextField()),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("country", models.CharField(db_index=True, max_length=100)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Maximum number of attendees",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "current_attendees",
                    models.PositiveIntegerField(
                        default=0, help_text="Current number of registered attendees"
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="events/banners/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("attended", "Attended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("confirmation_date", models.DateTimeField(blank=True, null=True)),
                ("dietary_requirements", models.TextField(blank=True)),
                ("special_requests", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Registration",
                "verbose_name_plural": "Registrations",
                "ordering": ["-registration_date"],
            },
        ),
    ]
