# Generated by Django 5.0.8 on 2025-10-19 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("bio", models.TextField(blank=True)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("website", models.URLField(blank=True)),
                ("twitter", models.CharField(blank=True, max_length=100)),
                ("linkedin", models.URLField(blank=True)),
                ("github", models.CharField(blank=True, max_length=100)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="speakers/profiles/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Speaker",
                "verbose_name_plural": "Speakers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("description", models.TextField()),
                (
                    "session_format",
                    models.CharField(
                        choices=[
                            ("talk", "Talk"),
                            ("workshop", "Workshop"),
                            ("panel", "Panel Discussion"),
                            ("lightning", "Lightning Talk"),
                            ("keynote", "Keynote"),
                        ],
                        default="talk",
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("all", "All Levels"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(db_index=True)),
                ("end_time", models.DateTimeField(db_index=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        help_text="Session duration in minutes"
                    ),
                ),
                ("room", models.CharField(blank=True, max_length=100)),
                (
                    "max_attendees",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum attendees (for workshops)",
                        null=True,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=200
                    ),
                ),
                ("slides_url", models.URLField(blank=True)),
                ("recording_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="events.event",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="tracks.track",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
                "ordering": ["start_time"],
            },
        ),
    ]
