# Generated by Django 5.0.8 on 2025-10-19 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("session_manager", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="speaker_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="speakers",
            field=models.ManyToManyField(
                related_name="sessions", to="session_manager.speaker"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["event", "start_time"], name="session_man_event_i_865479_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["track", "start_time"], name="session_man_track_i_0f751e_idx"
            ),
        ),
    ]
